plugins {
    alias(libs.plugins.android.application)
    id 'com.google.gms.google-services'

}

android {
    namespace 'lk.zenova.pawhope'
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId "lk.zenova.pawhope"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    // AndroidX & Core UI
    implementation libs.appcompat.v161
    implementation libs.material.v1110
    implementation libs.constraintlayout.v214
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.androidx.swiperefreshlayout

    // Google Play Services: Maps & Location
    implementation libs.play.services.maps
    implementation libs.play.services.location

    // Glide
    implementation libs.glide
    annotationProcessor libs.compiler

    // CircleImageView
    implementation libs.circleimageview

    // Gson
    implementation libs.gson

    // Testing
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit.v115
    androidTestImplementation libs.androidx.espresso.core.v351

}